import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import SidebarUI from "@/components/SidebarUI.js";
import { ENDPOINT_API, PATH_FRONT } from "@/utils/endpoints";
import { UserProvider } from "./userContext";
import SidebarLoginUI from "@/components/SidebarLoginUI"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="d-flex h-full flex-column flex-lg-row">
          <UserProvider>
            <SidebarLoginUI urlLogout={ENDPOINT_API.logout}></SidebarLoginUI>
            
            <div className="w-full h-screen overflow-y-scroll">
              {children}
            </div>
          </UserProvider>
        </div>
      </body>
    </html>
  );
}
